### ISSUE TITLE
Call to undefined method ElanEv\Driver\DfnVc::getRecordings()

### ISSUE THREAD

**Issue by tleilax** [virtUOS/studip-meeting#16]
Beim Aufruf des Plugins in einer Veranstaltung (aktuelle Version).

/cc @nimuelle

**Comment by nimuelle** [comment]
```
2018/03/07 11:10:17 [error] 29515#29515: *2249252 FastCGI sent in stderr: "PHP message: Error: Call to undefined method ElanEv\Driver\DfnVc::getRecordings() in /var/www/studip-4.0/public/plugins_packages/elan-ev/MeetingPlugin/app/views/index/_meetings.php:122
Stack trace:
#0 /var/www/studip-4.0/vendor/flexi/lib/php_template.php(46): require()
#1 /var/www/studip-4.0/vendor/flexi/lib/template.php(157): Flexi_PhpTemplate->_render()
#2 /var/www/studip-4.0/vendor/flexi/lib/template_factory.php(279): Flexi_Template->render(Array, NULL)
#3 /var/www/studip-4.0/vendor/flexi/lib/php_template.php(71): Flexi_TemplateFactory->render('index/_meetings', Array)
#4 /var/www/studip-4.0/public/plugins_packages/elan-ev/MeetingPlugin/app/views/index/index.php(20): Flexi_PhpTemplate->render_partial('index/_meetings', Array)
#5 /var/www/studip-4.0/vendor/flexi/lib/php_template.php(46): require('/var/www/studip...')
#6 /var/www/studip-4.0/vendor/flexi/lib/template.php(157): Flexi_PhpTemplate->_render()
#7 /var/www/studip-4.0/vendor/trails/trails.php(764): Flexi_Template->render()
#8 /var/www/studip-4.0" while reading response header from upstream, client: 134.106.68.93, server: elearning.uni-oldenburg.de, request: "GET /plugins.php/meetingplugin/index?cid=8f91dff542fcbfbdbd28ac1ae69cea51 HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "elearning.uni-oldenburg.de", referrer: "https://elearning.uni-oldenburg.de/dispatch.php/course/overview?cid=8f91dff542fcbfbdbd28ac1ae69cea51
```
