### ISSUE TITLE
Fehlermeldung bei nicht existierendem Meeting

### ISSUE THREAD

**Issue by schuettloeffel-elsa** [virtUOS/studip-meeting#288]
Öffnet man einen Link zu einem Meeting was nicht existiert, so wird eine unschöne Fehlermeldung geworfen:

> Fehler! Bitte wenden Sie sich an Ihren Systemadministrator.
> Call to a member function find() on null

Hier sollte der Fehler abgefangen werden und eine aussagekräftige Meldung erscheinen.

```
2021/08/11 09:51:22 [error] 4088515#4088515: *495203389 FastCGI sent in stderr: "PHP message: Error: Call to a member function find() on null in /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/room.php:72
Stack trace:
#0 /srv/studip_svn/4.6/vendor/trails/trails.php(557): RoomController->index_action('1553a6c47658914...', '467f8fe25f25daa...')
#1 /srv/studip_svn/4.6/app/controllers/studip_controller.php(110): Trails_Controller->perform('index/1553a6c47...')
#2 /srv/studip_svn/4.6/vendor/trails/trails.php(154): StudipController->perform('index/1553a6c47...')
#3 /srv/studip_svn/4.6/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('room/index/1553...')
#4 /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/MeetingPlugin.php(252): Trails_Dispatcher->dispatch('room/index/1553...')
#5 /srv/studip_svn/4.6/public/plugins.php(54): MeetingPlugin->perform('room/index/1553...')
#6 {main}" while reading response header from upstream, client: xxx, server: studip.uni-hannover.de, request: "GET /plugins.php/meetingplugin/room/index/1553a6c4765891477e4587a9d8a261f7/467f8fe25f25daa59978dafdd5f8a542?cancel_login=1 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php-fpm-studip.sock:", host: "studip.uni-hannover.de"
```

**Comment by ferishili** [comment]
Added via https://github.com/virtUOS/studip-meeting/commit/0c5ebc3a036dcdc66c75b01c6e272a47165aee7a
