### ISSUE TITLE
InvitationsLinks werden nicht gelöscht  wenn Meetings gelöscht werden

### ISSUE THREAD

**Issue by crosscodr** [virtUOS/studip-meeting#307]
Wenn meetings gelöscht werden, die einen InvitationsLink enthalten, werden diese Links nicht mitgelöscht.
Das kann dann später zu diesen Fehlern führen:
```
2021/09/14 13:17:18 [error] 2442798#2442798: *16958184 FastCGI sent in stderr: "PHP message:
 Error: Call to a member function find() on null in /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/app/controllers/room.php:72
Stack trace:
#0 /srv/studip_svn/4.6/vendor/trails/trails.php(557): RoomController->index_action('1553a6c47658914...', '467f8fe25f25daa...')
#1 /srv/studip_svn/4.6/app/controllers/studip_controller.php(110): Trails_Controller->perform('index/1553a6c47...')
#2 /srv/studip_svn/4.6/vendor/trails/trails.php(154): StudipController->perform('index/1553a6c47...')
#3 /srv/studip_svn/4.6/vendor/trails/trails.php(121): Trails_Dispatcher->map_uri_to_response('room/index/1553...')
#4 /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/MeetingPlugin.php(252): Trails_Dispatcher->dispatch('room/index/1553...')
#5 /srv/studip_svn/4.6/public/plugins.php(54): MeetingPlugin->perform('room/index/1553...')
#6 {main}" while reading response header from upstream,
 request: "GET /plugins.php/meetingplugin/room/index/xxxxxxxxxxx/xxxxxxxxxxxxxxxxxx?cancel_login=1 HTTP/1.1""
```
Die InvitationsLinks sollten mitgelöscht werden damit im room-controller gleich erkannt wird, das es das Meeting worauf gelinkt wurde gar nicht mehr gibt.

**Comment by crosscodr** [comment]
Hiermit kann man übriggebliebene einträge suchen
`select * from vc_invitations_links where meeting_id not in (select id from vc_meetings);`
und löschen:
`delete from vc_invitations_links where meeting_id not in (select id from vc_meetings);`
