### ISSUE TITLE
Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by crosscodr** [virtUOS/studip-meeting#336]
```
2021/10/12 11:12:47 [error] 2624605#2624605: *103621082 FastCGI sent in stderr: "PHP message: Meetings\Errors\Error: 23000: Konnte dem Meeting nicht beitreten, Kommunikation mit dem Meeting-Server fehlgeschlagen.
 (SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1634116367' for key 'expiration')
 in /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/lib/Errors/ErrorHandler.php:37
Stack trace:
#0 /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/lib/Errors/ExceptionHandler.php(59):
 Meetings\Errors\ErrorHandler->prepareResponseMessage(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Meetings\Errors\Error))
#1 [internal function]: Meetings\Errors\ExceptionHandler->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Meetings\Errors\Error))
#2 /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/vendor/slim/slim/Slim/App.php(701): call_user_func_array(Object(Meetings\Errors\ExceptionHandler), Array)
#3 /srv/studip_svn/4.6/public/plugins_packages/elan-ev/MeetingPlugin/vendor/slim/slim/Sl" while reading response header from upstream,
 request: "GET /plugins.php/meetingplugin/api/rooms/join/a851748aab8fec0b1e1f6eb67656e362/35168 HTTP/2.0",
 referrer: "https://studip.uni-hannover.de/plugins.php/meetingplugin/index?cid=a851748aab8fec0b1e1f6eb67656e362"
```

**Comment by crosscodr** [comment]
I didn't experienced this error by myself. But looking at referer and request, it should have happend when someone wants to join a room.

**Comment by ferishili** [comment]
> Hi @ferishili, thank you for your patch!
> 
> 

No problem ✌️
