### ISSUE TITLE
Presentation does not show up

### ISSUE THREAD

**Issue by playernine** [virtUOS/studip-meeting#348]
Stud.IP Version: 4.6.1 ( PHP v7.2.24-0ubuntu0.18.04.10 )
Meeting Plugin Version: 2.68
BBB Version 2.3.14

After starting the Meeting no presentation appears.

On the BBB Server I see the following error message:

/var/log/bigbluebutton/bbb-web.log

`2021-12-03T17:10:58.466+01:00 INFO  o.b.p.DocumentConversionServiceImp -  --analytics-- data={"current":true,"filename":"blanc.pdf","logCode":"presentation_conversion_start","authzToken":"preupload-download-authz-token","meetingId":"1ebf62fb581f65bd0ef7b1b1256d06f942fdcf43-1638547853289","message":"Start presentation conversion.","podId":"DEFAULT_PRESENTATION_POD","presId":"bb2c0df90e4ced6974d709e6bdd4b58b1f54f7ab-1638547853314"}
2021-12-03T17:10:58.467+01:00 INFO  o.b.p.SupportedDocumentFilter - Received supported file /var/bigbluebutton/1ebf62fb581f65bd0ef7b1b1256d06f942fdcf43-1638547853289/1ebf62fb581f65bd0ef7b1b1256d06f942fdcf43-1638547853289/bb2c0df90e4ced6974d709e6bdd4b58b1f54f7ab-1638547853314/bb2c0df90e4ced6974d709e6bdd4b58b1f54f7ab-1638547853314.pdf
2021-12-03T17:10:58.482+01:00 ERROR o.b.p.h.PdfPageCounterHandler - Exception counting images
java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at org.bigbluebutton.presentation.handlers.PdfPageCounterHandler.numberOfPages(PdfPageCounterHandler.java:42)
	at org.bigbluebutton.presentation.imp.PdfPageCounter.countNumberOfPages(PdfPageCounter.java:55)
	at org.bigbluebutton.presentation.imp.PageCounterService.countPages(PageCounterService.java:74)
	at org.bigbluebutton.presentation.imp.PageCounterService.determineNumberOfPages(PageCounterService.java:37)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor.determineNumberOfPages(PresentationFileProcessor.java:152)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor.processUploadedPresentation(PresentationFileProcessor.java:81)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor.access$000(PresentationFileProcessor.java:22)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor$1.run(PresentationFileProcessor.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-12-03T17:10:58.482+01:00 ERROR o.b.p.imp.PresentationFileProcessor -  --analytics-- data={"filename":"blanc.pdf","logCode":"determine_num_pages_failed","meetingId":"1ebf62fb581f65bd0ef7b1b1256d06f942fdcf43-1638547853289","message":"Failed to determine number of pages.","podId":"DEFAULT_PRESENTATION_POD","presId":"bb2c0df90e4ced6974d709e6bdd4b58b1f54f7ab-1638547853314"}
org.bigbluebutton.presentation.imp.CountingPageException: Exception while trying to determine number of pages.
	at org.bigbluebutton.presentation.imp.PageCounterService.isNumberOfPagesValid(PageCounterService.java:49)
	at org.bigbluebutton.presentation.imp.PageCounterService.determineNumberOfPages(PageCounterService.java:42)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor.determineNumberOfPages(PresentationFileProcessor.java:152)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor.processUploadedPresentation(PresentationFileProcessor.java:81)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor.access$000(PresentationFileProcessor.java:22)
	at org.bigbluebutton.presentation.imp.PresentationFileProcessor$1.run(PresentationFileProcessor.java:64)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-12-03T17:10:58.483+01:00 INFO  o.b.p.imp.PresentationFileProcessor -  --analytics-- data={"filename":"blanc.pdf","num_pages":0,"logCode":"presentation_conversion_num_pages","authzToken":"preupload-download-authz-token","meetingId":"1ebf62fb581f65bd0ef7b1b1256d06f942fdcf43-1638547853289","message":"Presentation conversion number of pages.","podId":"DEFAULT_PRESENTATION_POD","presId":"bb2c0df90e4ced6974d709e6bdd4b58b1f54f7ab-1638547853314"}`

I see no errors in the php_error.log

If I use the URL of the BBB request to fetch the PDF it show up correctly in my browser.

We have a second Stud.IP Server running:

Stud.IP Version: 4.4.6 ( PHP v7.2.24-0ubuntu0.18.04.10 )
Meeting Plugin Version: 2.68
BBB Version 2.3.14

With this Server it works.

This server is older and has more php modules installed.

may be it is something like imagick or something else in need?

**Comment by playernine** [comment]
We found the problem.
The Stud.IP nobody role for the  Meeting Plugin was missing.
